import 'dart:io';
import 'dart:typed_data';

import 'package:excel/excel.dart' as xl;
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../core/formatters.dart';
import '../data/app_database.dart';
import '../data/history_repository.dart';

/// Builds the History statement as a PDF or an Excel workbook, entirely
/// on-device, and hands it to the Android share sheet (WhatsApp, e-mail,
/// Drive, "Save to device"...). Intended for the owner or their CA.
class HistoryExportService {
  HistoryExportService._();

  /// Safety limit so a huge range cannot exhaust phone memory.
  static const int maxRows = 20000;

  static String kindLabel(String kind) {
    switch (kind) {
      case 'invoice':
        return 'Invoice sale';
      case 'credit':
        return 'Credit given';
      case 'payment':
        return 'Payment received';
      default:
        return kind;
    }
  }

  static String _num(double v) => v.toStringAsFixed(2);

  static String fileName(DateTime first, DateTime last, String ext) {
    String d(DateTime x) =>
        '${x.year}${x.month.toString().padLeft(2, '0')}${x.day.toString().padLeft(2, '0')}';
    return 'ShopHisab_Statement_${d(first)}_to_${d(last)}.$ext';
  }

  static ({double sales, double credit, double received}) _totals(
    List<ExportRow> rows,
  ) {
    var s = 0.0, c = 0.0, r = 0.0;
    for (final x in rows) {
      s += x.sales;
      c += x.credit;
      r += x.received;
    }
    return (sales: s, credit: c, received: r);
  }

  static List<_Day> _daily(List<ExportRow> rows) {
    final map = <DateTime, _Day>{};
    for (final x in rows) {
      final key = DateTime(x.time.year, x.time.month, x.time.day);
      final d = map.putIfAbsent(key, () => _Day(key));
      d.sales += x.sales;
      d.credit += x.credit;
      d.received += x.received;
      d.records++;
    }
    final list = map.values.toList()..sort((a, b) => a.date.compareTo(b.date));
    return list;
  }

  // ------------------------------------------------------------------ PDF

  static Future<Uint8List> buildPdf({
    required BusinessProfile? business,
    required List<ExportRow> rows,
    required DateTime first,
    required DateTime last,
  }) async {
    final regular = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSans-Regular.ttf'),
    );
    final bold = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSans-Bold.ttf'),
    );
    final doc = pw.Document(
      title: 'ShopHisab statement',
      theme: pw.ThemeData.withFont(base: regular, bold: bold),
    );
    const brand = PdfColor.fromInt(0xFF0E6E4E);
    const light = PdfColor.fromInt(0xFFE6F2EC);
    final totals = _totals(rows);
    final days = _daily(rows);
    final generated = AppFormatters.dateTimeStr(DateTime.now());

    pw.Widget cell(
      String text, {
      bool header = false,
      pw.TextAlign align = pw.TextAlign.left,
      PdfColor? color,
    }) =>
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 4),
          child: pw.Text(
            text,
            textAlign: align,
            style: pw.TextStyle(
              fontSize: 8.5,
              fontWeight: header ? pw.FontWeight.bold : pw.FontWeight.normal,
              color: header ? PdfColors.white : color,
            ),
          ),
        );

    pw.Widget statBox(String label, String value, PdfColor color) => pw.Expanded(
          child: pw.Container(
            margin: const pw.EdgeInsets.only(right: 6),
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              color: light,
              borderRadius: pw.BorderRadius.circular(4),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(label, style: const pw.TextStyle(fontSize: 8)),
                pw.SizedBox(height: 3),
                pw.Text(
                  value,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                    color: color,
                  ),
                ),
              ],
            ),
          ),
        );

    final range =
        '${AppFormatters.date(first)} - ${AppFormatters.date(last)}';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        footer: (ctx) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by ShopHisab on $generated',
              style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey700),
            ),
            pw.Text(
              'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
              style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey700),
            ),
          ],
        ),
        build: (ctx) => [
          pw.Text(
            business?.businessName ?? 'ShopHisab',
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
              color: brand,
            ),
          ),
          if (business != null && business.address.isNotEmpty)
            pw.Text(business.address, style: const pw.TextStyle(fontSize: 9)),
          if (business != null && business.phone.isNotEmpty)
            pw.Text('Phone: ${business.phone}',
                style: const pw.TextStyle(fontSize: 9)),
          if (business != null &&
              (business.gstNumber ?? '').trim().isNotEmpty)
            pw.Text('GSTIN: ${business.gstNumber}',
                style: const pw.TextStyle(fontSize: 9)),
          pw.SizedBox(height: 10),
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(8),
            color: brand,
            child: pw.Text(
              'Transaction statement  |  $range',
              style: pw.TextStyle(
                color: PdfColors.white,
                fontWeight: pw.FontWeight.bold,
                fontSize: 11,
              ),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              statBox('Invoice sales', AppFormatters.money(totals.sales),
                  brand),
              statBox('Credit given', AppFormatters.money(totals.credit),
                  const PdfColor.fromInt(0xFFC2410C)),
              statBox('Money received',
                  AppFormatters.money(totals.received),
                  const PdfColor.fromInt(0xFF1D4ED8)),
              statBox('Records', '${rows.length}', PdfColors.grey800),
            ],
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Sales, credit and collections are separate measures. Payments linked to an invoice are counted once.',
            style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 12),
          pw.Text('Day-wise summary',
              style:
                  pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.4),
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(1),
              2: const pw.FlexColumnWidth(2),
              3: const pw.FlexColumnWidth(2),
              4: const pw.FlexColumnWidth(2),
            },
            children: [
              pw.TableRow(
                repeat: true,
                decoration: const pw.BoxDecoration(color: brand),
                children: [
                  cell('Date', header: true),
                  cell('Records', header: true, align: pw.TextAlign.right),
                  cell('Invoice sales', header: true, align: pw.TextAlign.right),
                  cell('Credit given', header: true, align: pw.TextAlign.right),
                  cell('Money received',
                      header: true, align: pw.TextAlign.right),
                ],
              ),
              ...days.map(
                (d) => pw.TableRow(
                  children: [
                    cell(AppFormatters.date(d.date)),
                    cell('${d.records}', align: pw.TextAlign.right),
                    cell(_num(d.sales), align: pw.TextAlign.right),
                    cell(_num(d.credit), align: pw.TextAlign.right),
                    cell(_num(d.received), align: pw.TextAlign.right),
                  ],
                ),
              ),
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: light),
                children: [
                  cell('TOTAL', header: false),
                  cell('${rows.length}', align: pw.TextAlign.right),
                  cell(_num(totals.sales), align: pw.TextAlign.right),
                  cell(_num(totals.credit), align: pw.TextAlign.right),
                  cell(_num(totals.received), align: pw.TextAlign.right),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 16),
          pw.Text('All transactions',
              style:
                  pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.4),
            columnWidths: {
              0: const pw.FlexColumnWidth(2.2),
              1: const pw.FlexColumnWidth(2),
              2: const pw.FlexColumnWidth(2.6),
              3: const pw.FlexColumnWidth(2),
            },
            children: [
              pw.TableRow(
                repeat: true,
                decoration: const pw.BoxDecoration(color: brand),
                children: [
                  cell('Date & time', header: true),
                  cell('Type', header: true),
                  cell('Reference / details', header: true),
                  cell('Amount', header: true, align: pw.TextAlign.right),
                ],
              ),
              ...rows.map(
                (r) => pw.TableRow(
                  children: [
                    cell(AppFormatters.dateTimeStr(r.time)),
                    cell(kindLabel(r.kind)),
                    cell(
                      r.details.trim().isEmpty
                          ? r.reference
                          : '${r.reference}\n${r.details}',
                    ),
                    cell(_num(r.amount), align: pw.TextAlign.right),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
    return doc.save();
  }

  // ---------------------------------------------------------------- Excel

  static Uint8List buildXlsx({
    required BusinessProfile? business,
    required List<ExportRow> rows,
    required DateTime first,
    required DateTime last,
  }) {
    final book = xl.Excel.createExcel();
    final summary = book['Summary'];
    final daily = book['Day-wise'];
    final tx = book['Transactions'];
    book.delete('Sheet1');

    final head = xl.CellStyle(
      bold: true,
      fontColorHex: xl.ExcelColor.fromHexString('FFFFFFFF'),
      backgroundColorHex: xl.ExcelColor.fromHexString('FF0E6E4E'),
      horizontalAlign: xl.HorizontalAlign.Center,
    );
    final bold = xl.CellStyle(bold: true);
    final money = xl.CellStyle(numberFormat: xl.NumFormat.standard_2);
    final moneyBold =
        xl.CellStyle(bold: true, numberFormat: xl.NumFormat.standard_2);

    void put(xl.Sheet s, int c, int r, xl.CellValue v, [xl.CellStyle? st]) {
      final cell =
          s.cell(xl.CellIndex.indexByColumnRow(columnIndex: c, rowIndex: r));
      cell.value = v;
      if (st != null) cell.cellStyle = st;
    }

    xl.CellValue text(String s) => xl.TextCellValue(s);
    xl.CellValue dbl(double v) => xl.DoubleCellValue(v);

    final totals = _totals(rows);
    final days = _daily(rows);

    // --- Summary sheet
    var r = 0;
    put(summary, 0, r++, text(business?.businessName ?? 'ShopHisab'), bold);
    if (business != null && business.address.isNotEmpty) {
      put(summary, 0, r++, text(business.address));
    }
    if (business != null && business.phone.isNotEmpty) {
      put(summary, 0, r++, text('Phone: ${business.phone}'));
    }
    if (business != null && (business.gstNumber ?? '').trim().isNotEmpty) {
      put(summary, 0, r++, text('GSTIN: ${business.gstNumber}'));
    }
    r++;
    put(summary, 0, r, text('Period'), bold);
    put(summary, 1, r++,
        text('${AppFormatters.date(first)} to ${AppFormatters.date(last)}'));
    put(summary, 0, r, text('Generated'), bold);
    put(summary, 1, r++, text(AppFormatters.dateTimeStr(DateTime.now())));
    put(summary, 0, r, text('Currency'), bold);
    put(summary, 1, r++, text(AppFormatters.currencyCode));
    r++;
    put(summary, 0, r, text('Measure'), head);
    put(summary, 1, r++, text('Amount'), head);
    put(summary, 0, r, text('Invoice sales'));
    put(summary, 1, r++, dbl(totals.sales), money);
    put(summary, 0, r, text('Credit given'));
    put(summary, 1, r++, dbl(totals.credit), money);
    put(summary, 0, r, text('Money received'));
    put(summary, 1, r++, dbl(totals.received), money);
    put(summary, 0, r, text('Number of records'));
    put(summary, 1, r++, xl.IntCellValue(rows.length));
    r++;
    put(
      summary,
      0,
      r,
      text(
        'Sales, credit and collections are separate measures. Payments linked to an invoice are counted once.',
      ),
    );
    summary.setColumnWidth(0, 28);
    summary.setColumnWidth(1, 30);

    // --- Day-wise sheet
    const dHead = [
      'Date',
      'Records',
      'Invoice sales',
      'Credit given',
      'Money received',
    ];
    for (var c = 0; c < dHead.length; c++) {
      put(daily, c, 0, text(dHead[c]), head);
    }
    var dr = 1;
    for (final d in days) {
      put(daily, 0, dr, xl.DateCellValue.fromDateTime(d.date));
      put(daily, 1, dr, xl.IntCellValue(d.records));
      put(daily, 2, dr, dbl(d.sales), money);
      put(daily, 3, dr, dbl(d.credit), money);
      put(daily, 4, dr, dbl(d.received), money);
      dr++;
    }
    put(daily, 0, dr, text('TOTAL'), bold);
    put(daily, 1, dr, xl.IntCellValue(rows.length), bold);
    put(daily, 2, dr, dbl(totals.sales), moneyBold);
    put(daily, 3, dr, dbl(totals.credit), moneyBold);
    put(daily, 4, dr, dbl(totals.received), moneyBold);
    for (var c = 0; c < dHead.length; c++) {
      daily.setColumnWidth(c, c == 0 ? 16 : 18);
    }

    // --- Transactions sheet
    const tHead = [
      'Date',
      'Time',
      'Type',
      'Reference / customer',
      'Details',
      'Amount',
      'Invoice sales',
      'Credit given',
      'Money received',
    ];
    for (var c = 0; c < tHead.length; c++) {
      put(tx, c, 0, text(tHead[c]), head);
    }
    var tr = 1;
    for (final x in rows) {
      final hh = x.time.hour.toString().padLeft(2, '0');
      final mm = x.time.minute.toString().padLeft(2, '0');
      put(tx, 0, tr, xl.DateCellValue.fromDateTime(x.time));
      put(tx, 1, tr, text('$hh:$mm'));
      put(tx, 2, tr, text(kindLabel(x.kind)));
      put(tx, 3, tr, text(x.reference));
      put(tx, 4, tr, text(x.details));
      put(tx, 5, tr, dbl(x.amount), money);
      put(tx, 6, tr, dbl(x.sales), money);
      put(tx, 7, tr, dbl(x.credit), money);
      put(tx, 8, tr, dbl(x.received), money);
      tr++;
    }
    put(tx, 0, tr, text('TOTAL'), bold);
    put(tx, 6, tr, dbl(totals.sales), moneyBold);
    put(tx, 7, tr, dbl(totals.credit), moneyBold);
    put(tx, 8, tr, dbl(totals.received), moneyBold);
    const widths = [14.0, 8.0, 18.0, 28.0, 42.0, 14.0, 15.0, 15.0, 16.0];
    for (var c = 0; c < widths.length; c++) {
      tx.setColumnWidth(c, widths[c]);
    }

    final bytes = book.encode();
    if (bytes == null) {
      throw StateError('Could not build the Excel file.');
    }
    return Uint8List.fromList(bytes);
  }

  // ---------------------------------------------------------------- Share

  /// Writes [bytes] to a temp file and opens the Android share sheet.
  static Future<void> saveAndShare({
    required Uint8List bytes,
    required String name,
    required String mimeType,
  }) async {
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$name');
    await file.writeAsBytes(bytes, flush: true);
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path, mimeType: mimeType, name: name)],
        subject: 'ShopHisab statement',
        text: 'ShopHisab transaction statement',
      ),
    );
  }
}

class _Day {
  _Day(this.date);
  final DateTime date;
  double sales = 0, credit = 0, received = 0;
  int records = 0;
}
