import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../core/formatters.dart';
import '../data/app_database.dart';
import '../data/history_repository.dart';
import 'simple_xlsx.dart';

/// Builds the History statement as a PDF or an Excel workbook, entirely
/// on-device, and hands it to the Android share sheet (WhatsApp, e-mail,
/// Drive, "Save to device"...). Intended for the owner or their CA.
class HistoryExportService {
  HistoryExportService._();

  /// Safety limit so a huge range cannot exhaust phone memory.
  static const int maxRows = 20000;

  static String kindLabel(String kind) {
    switch (kind) {
      case 'invoice':
        return 'Invoice sale';
      case 'credit':
        return 'Credit given';
      case 'payment':
        return 'Payment received';
      default:
        return kind;
    }
  }

  static String _num(double v) => v.toStringAsFixed(2);

  static String fileName(DateTime first, DateTime last, String ext) {
    String d(DateTime x) =>
        '${x.year}${x.month.toString().padLeft(2, '0')}${x.day.toString().padLeft(2, '0')}';
    return 'ShopHisab_Statement_${d(first)}_to_${d(last)}.$ext';
  }

  static ({double sales, double credit, double received}) _totals(
    List<ExportRow> rows,
  ) {
    var s = 0.0, c = 0.0, r = 0.0;
    for (final x in rows) {
      s += x.sales;
      c += x.credit;
      r += x.received;
    }
    return (sales: s, credit: c, received: r);
  }

  static List<_Day> _daily(List<ExportRow> rows) {
    final map = <DateTime, _Day>{};
    for (final x in rows) {
      final key = DateTime(x.time.year, x.time.month, x.time.day);
      final d = map.putIfAbsent(key, () => _Day(key));
      d.sales += x.sales;
      d.credit += x.credit;
      d.received += x.received;
      d.records++;
    }
    final list = map.values.toList()..sort((a, b) => a.date.compareTo(b.date));
    return list;
  }

  // ------------------------------------------------------------------ PDF

  static Future<Uint8List> buildPdf({
    required BusinessProfile? business,
    required List<ExportRow> rows,
    required DateTime first,
    required DateTime last,
  }) async {
    final regular = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSans-Regular.ttf'),
    );
    final bold = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSans-Bold.ttf'),
    );
    final doc = pw.Document(
      title: 'ShopHisab statement',
      theme: pw.ThemeData.withFont(base: regular, bold: bold),
    );
    const brand = PdfColor.fromInt(0xFF0E6E4E);
    const light = PdfColor.fromInt(0xFFE6F2EC);
    final totals = _totals(rows);
    final days = _daily(rows);
    final generated = AppFormatters.dateTimeStr(DateTime.now());

    pw.Widget cell(
      String text, {
      bool header = false,
      pw.TextAlign align = pw.TextAlign.left,
      PdfColor? color,
    }) =>
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 4),
          child: pw.Text(
            text,
            textAlign: align,
            style: pw.TextStyle(
              fontSize: 8.5,
              fontWeight: header ? pw.FontWeight.bold : pw.FontWeight.normal,
              color: header ? PdfColors.white : color,
            ),
          ),
        );

    pw.Widget statBox(String label, String value, PdfColor color) => pw.Expanded(
          child: pw.Container(
            margin: const pw.EdgeInsets.only(right: 6),
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              color: light,
              borderRadius: pw.BorderRadius.circular(4),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(label, style: const pw.TextStyle(fontSize: 8)),
                pw.SizedBox(height: 3),
                pw.Text(
                  value,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                    color: color,
                  ),
                ),
              ],
            ),
          ),
        );

    final range =
        '${AppFormatters.date(first)} - ${AppFormatters.date(last)}';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        footer: (ctx) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by ShopHisab on $generated',
              style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey700),
            ),
            pw.Text(
              'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
              style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey700),
            ),
          ],
        ),
        build: (ctx) => [
          pw.Text(
            business?.businessName ?? 'ShopHisab',
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
              color: brand,
            ),
          ),
          if (business != null && business.address.isNotEmpty)
            pw.Text(business.address, style: const pw.TextStyle(fontSize: 9)),
          if (business != null && business.phone.isNotEmpty)
            pw.Text('Phone: ${business.phone}',
                style: const pw.TextStyle(fontSize: 9)),
          if (business != null &&
              (business.gstNumber ?? '').trim().isNotEmpty)
            pw.Text('GSTIN: ${business.gstNumber}',
                style: const pw.TextStyle(fontSize: 9)),
          pw.SizedBox(height: 10),
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(8),
            color: brand,
            child: pw.Text(
              'Transaction statement  |  $range',
              style: pw.TextStyle(
                color: PdfColors.white,
                fontWeight: pw.FontWeight.bold,
                fontSize: 11,
              ),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              statBox('Invoice sales', AppFormatters.money(totals.sales),
                  brand),
              statBox('Credit given', AppFormatters.money(totals.credit),
                  const PdfColor.fromInt(0xFFC2410C)),
              statBox('Money received',
                  AppFormatters.money(totals.received),
                  const PdfColor.fromInt(0xFF1D4ED8)),
              statBox('Records', '${rows.length}', PdfColors.grey800),
            ],
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Sales, credit and collections are separate measures. Payments linked to an invoice are counted once.',
            style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 12),
          pw.Text('Day-wise summary',
              style:
                  pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.4),
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(1),
              2: const pw.FlexColumnWidth(2),
              3: const pw.FlexColumnWidth(2),
              4: const pw.FlexColumnWidth(2),
            },
            children: [
              pw.TableRow(
                repeat: true,
                decoration: const pw.BoxDecoration(color: brand),
                children: [
                  cell('Date', header: true),
                  cell('Records', header: true, align: pw.TextAlign.right),
                  cell('Invoice sales', header: true, align: pw.TextAlign.right),
                  cell('Credit given', header: true, align: pw.TextAlign.right),
                  cell('Money received',
                      header: true, align: pw.TextAlign.right),
                ],
              ),
              ...days.map(
                (d) => pw.TableRow(
                  children: [
                    cell(AppFormatters.date(d.date)),
                    cell('${d.records}', align: pw.TextAlign.right),
                    cell(_num(d.sales), align: pw.TextAlign.right),
                    cell(_num(d.credit), align: pw.TextAlign.right),
                    cell(_num(d.received), align: pw.TextAlign.right),
                  ],
                ),
              ),
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: light),
                children: [
                  cell('TOTAL', header: false),
                  cell('${rows.length}', align: pw.TextAlign.right),
                  cell(_num(totals.sales), align: pw.TextAlign.right),
                  cell(_num(totals.credit), align: pw.TextAlign.right),
                  cell(_num(totals.received), align: pw.TextAlign.right),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 16),
          pw.Text('All transactions',
              style:
                  pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.4),
            columnWidths: {
              0: const pw.FlexColumnWidth(2.2),
              1: const pw.FlexColumnWidth(2),
              2: const pw.FlexColumnWidth(2.6),
              3: const pw.FlexColumnWidth(2),
            },
            children: [
              pw.TableRow(
                repeat: true,
                decoration: const pw.BoxDecoration(color: brand),
                children: [
                  cell('Date & time', header: true),
                  cell('Type', header: true),
                  cell('Reference / details', header: true),
                  cell('Amount', header: true, align: pw.TextAlign.right),
                ],
              ),
              ...rows.map(
                (r) => pw.TableRow(
                  children: [
                    cell(AppFormatters.dateTimeStr(r.time)),
                    cell(kindLabel(r.kind)),
                    cell(
                      r.details.trim().isEmpty
                          ? r.reference
                          : '${r.reference}\n${r.details}',
                    ),
                    cell(_num(r.amount), align: pw.TextAlign.right),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
    return doc.save();
  }

  // ---------------------------------------------------------------- Excel

  static Uint8List buildXlsx({
    required BusinessProfile? business,
    required List<ExportRow> rows,
    required DateTime first,
    required DateTime last,
  }) {
    final totals = _totals(rows);
    final days = _daily(rows);

    XCell h(String s) => XCell(s, XStyle.header);
    XCell b(String s) => XCell(s, XStyle.bold);
    XCell t(String s) => XCell(s);
    XCell m(double v) => XCell(v, XStyle.money);
    XCell mb(double v) => XCell(v, XStyle.moneyBold);

    // --- Summary sheet
    final summary = XSheet('Summary');
    summary.addRow([b(business?.businessName ?? 'ShopHisab')]);
    if (business != null && business.address.isNotEmpty) {
      summary.addRow([t(business.address)]);
    }
    if (business != null && business.phone.isNotEmpty) {
      summary.addRow([t('Phone: ${business.phone}')]);
    }
    if (business != null && (business.gstNumber ?? '').trim().isNotEmpty) {
      summary.addRow([t('GSTIN: ${business.gstNumber}')]);
    }
    summary.addRow([]);
    summary.addRow([
      b('Period'),
      t('${AppFormatters.date(first)} to ${AppFormatters.date(last)}'),
    ]);
    summary.addRow([
      b('Generated'),
      t(AppFormatters.dateTimeStr(DateTime.now())),
    ]);
    summary.addRow([b('Currency'), t(AppFormatters.currencyCode)]);
    summary.addRow([]);
    summary.addRow([h('Measure'), h('Amount')]);
    summary.addRow([t('Invoice sales'), m(totals.sales)]);
    summary.addRow([t('Credit given'), m(totals.credit)]);
    summary.addRow([t('Money received'), m(totals.received)]);
    summary.addRow([t('Number of records'), XCell(rows.length)]);
    summary.addRow([]);
    summary.addRow([
      t(
        'Sales, credit and collections are separate measures. Payments linked to an invoice are counted once.',
      ),
    ]);
    summary.columnWidths[0] = 28;
    summary.columnWidths[1] = 32;

    // --- Day-wise sheet
    final daily = XSheet('Day-wise', freezeHeader: true);
    daily.addRow([
      h('Date'),
      h('Records'),
      h('Invoice sales'),
      h('Credit given'),
      h('Money received'),
    ]);
    for (final d in days) {
      daily.addRow([
        XCell(d.date, XStyle.date),
        XCell(d.records),
        m(d.sales),
        m(d.credit),
        m(d.received),
      ]);
    }
    daily.addRow([
      b('TOTAL'),
      XCell(rows.length, XStyle.bold),
      mb(totals.sales),
      mb(totals.credit),
      mb(totals.received),
    ]);
    daily.columnWidths.addAll({0: 16, 1: 12, 2: 18, 3: 18, 4: 18});

    // --- Transactions sheet
    final tx = XSheet('Transactions', freezeHeader: true);
    tx.addRow([
      h('Date'),
      h('Time'),
      h('Type'),
      h('Reference / customer'),
      h('Details'),
      h('Amount'),
      h('Invoice sales'),
      h('Credit given'),
      h('Money received'),
    ]);
    for (final x in rows) {
      final hh = x.time.hour.toString().padLeft(2, '0');
      final mm = x.time.minute.toString().padLeft(2, '0');
      tx.addRow([
        XCell(x.time, XStyle.date),
        t('$hh:$mm'),
        t(kindLabel(x.kind)),
        t(x.reference),
        t(x.details),
        m(x.amount),
        m(x.sales),
        m(x.credit),
        m(x.received),
      ]);
    }
    tx.addRow([
      b('TOTAL'),
      null,
      null,
      null,
      null,
      null,
      mb(totals.sales),
      mb(totals.credit),
      mb(totals.received),
    ]);
    tx.columnWidths.addAll({
      0: 14,
      1: 8,
      2: 18,
      3: 28,
      4: 42,
      5: 14,
      6: 15,
      7: 15,
      8: 16,
    });

    return SimpleXlsx.build([summary, daily, tx]);
  }

  // ---------------------------------------------------------------- Share

  /// Writes [bytes] to a temp file and opens the Android share sheet.
  static Future<void> saveAndShare({
    required Uint8List bytes,
    required String name,
    required String mimeType,
  }) async {
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$name');
    await file.writeAsBytes(bytes, flush: true);
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path, mimeType: mimeType, name: name)],
        subject: 'ShopHisab statement',
        text: 'ShopHisab transaction statement',
      ),
    );
  }
}

class _Day {
  _Day(this.date);
  final DateTime date;
  double sales = 0, credit = 0, received = 0;
  int records = 0;
}
