import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../core/formatters.dart';
import '../data/app_database.dart';

/// Builds a clean, professional invoice PDF entirely on-device - no server,
/// no template download, works with zero internet connectivity.
class PdfInvoiceService {
  static Future<Uint8List> build({
    required BusinessProfile business,
    required Invoice invoice,
    required List<InvoiceItem> items,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(business.businessName,
                          style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                      if (business.address.isNotEmpty) pw.Text(business.address),
                      if (business.phone.isNotEmpty) pw.Text('Phone: ${business.phone}'),
                      if (business.gstNumber != null) pw.Text('GSTIN: ${business.gstNumber}'),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('INVOICE',
                          style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
                      pw.Text(invoice.invoiceNumber),
                      pw.Text(AppFormatters.date(invoice.invoiceDate)),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 24),
              pw.Text('Bill to:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(invoice.customerNameSnapshot),
              if (invoice.dueDate != null)
                pw.Text('Due date: ${AppFormatters.date(invoice.dueDate!)}'),
              pw.SizedBox(height: 20),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                columnWidths: const {
                  0: pw.FlexColumnWidth(4),
                  1: pw.FlexColumnWidth(1.2),
                  2: pw.FlexColumnWidth(1.6),
                  3: pw.FlexColumnWidth(1.6),
                },
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                    children: [
                      _cell('Description', bold: true),
                      _cell('Qty', bold: true),
                      _cell('Rate', bold: true),
                      _cell('Amount', bold: true),
                    ],
                  ),
                  ...items.map((item) => pw.TableRow(children: [
                        _cell(item.description),
                        _cell(item.qty % 1 == 0 ? item.qty.toStringAsFixed(0) : item.qty.toString()),
                        _cell(AppFormatters.money(item.unitPrice)),
                        _cell(AppFormatters.money(item.lineTotal)),
                      ])),
                ],
              ),
              pw.SizedBox(height: 16),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.SizedBox(
                  width: 220,
                  child: pw.Column(
                    children: [
                      _totalsRow('Subtotal', invoice.subtotal),
                      _totalsRow('Discount', -invoice.discount),
                      _totalsRow('Tax (${invoice.taxPercent.toStringAsFixed(1)}%)',
                          invoice.total - (invoice.subtotal - invoice.discount)),
                      pw.Divider(),
                      _totalsRow('Total', invoice.total, bold: true),
                    ],
                  ),
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Status: ${invoice.status.name.toUpperCase()}',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              if (invoice.notes.isNotEmpty) ...[
                pw.SizedBox(height: 12),
                pw.Text('Notes: ${invoice.notes}'),
              ],
              pw.SizedBox(height: 28),
              pw.Center(
                child: pw.Text(
                  'Generated by BusinessOS - Your Shop. Your Data. Always Available.',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                ),
              ),
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  static pw.Widget _cell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text,
          style: pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
    );
  }

  static pw.Widget _totalsRow(String label, double value, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label,
              style: pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
          pw.Text(AppFormatters.money(value),
              style: pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
        ],
      ),
    );
  }
}
