/// Country dial codes for the phone number field. India is first since
/// this app is built for Indian shopkeepers, but the full list is included
/// since a shop's customers or the owner themselves may need another
/// country code (NRI customers, imported goods suppliers, etc).
class CountryCode {
  const CountryCode(this.name, this.iso, this.dialCode);
  final String name;
  final String iso;
  final String dialCode;

  String get label => '$name ($dialCode)';
}

const List<CountryCode> countryCodes = [
  CountryCode('India', 'IN', '+91'),
  CountryCode('United States', 'US', '+1'),
  CountryCode('United Kingdom', 'GB', '+44'),
  CountryCode('United Arab Emirates', 'AE', '+971'),
  CountryCode('Saudi Arabia', 'SA', '+966'),
  CountryCode('Qatar', 'QA', '+974'),
  CountryCode('Kuwait', 'KW', '+965'),
  CountryCode('Bahrain', 'BH', '+973'),
  CountryCode('Oman', 'OM', '+968'),
  CountryCode('Singapore', 'SG', '+65'),
  CountryCode('Malaysia', 'MY', '+60'),
  CountryCode('Australia', 'AU', '+61'),
  CountryCode('Canada', 'CA', '+1'),
  CountryCode('Nepal', 'NP', '+977'),
  CountryCode('Bangladesh', 'BD', '+880'),
  CountryCode('Pakistan', 'PK', '+92'),
  CountryCode('Sri Lanka', 'LK', '+94'),
  CountryCode('China', 'CN', '+86'),
  CountryCode('Japan', 'JP', '+81'),
  CountryCode('South Korea', 'KR', '+82'),
  CountryCode('Indonesia', 'ID', '+62'),
  CountryCode('Thailand', 'TH', '+66'),
  CountryCode('Vietnam', 'VN', '+84'),
  CountryCode('Philippines', 'PH', '+63'),
  CountryCode('Hong Kong', 'HK', '+852'),
  CountryCode('Afghanistan', 'AF', '+93'),
  CountryCode('Albania', 'AL', '+355'),
  CountryCode('Algeria', 'DZ', '+213'),
  CountryCode('Argentina', 'AR', '+54'),
  CountryCode('Armenia', 'AM', '+374'),
  CountryCode('Austria', 'AT', '+43'),
  CountryCode('Azerbaijan', 'AZ', '+994'),
  CountryCode('Belarus', 'BY', '+375'),
  CountryCode('Belgium', 'BE', '+32'),
  CountryCode('Bhutan', 'BT', '+975'),
  CountryCode('Bolivia', 'BO', '+591'),
  CountryCode('Bosnia and Herzegovina', 'BA', '+387'),
  CountryCode('Brazil', 'BR', '+55'),
  CountryCode('Brunei', 'BN', '+673'),
  CountryCode('Bulgaria', 'BG', '+359'),
  CountryCode('Cambodia', 'KH', '+855'),
  CountryCode('Chile', 'CL', '+56'),
  CountryCode('Colombia', 'CO', '+57'),
  CountryCode('Croatia', 'HR', '+385'),
  CountryCode('Cyprus', 'CY', '+357'),
  CountryCode('Czech Republic', 'CZ', '+420'),
  CountryCode('Denmark', 'DK', '+45'),
  CountryCode('Egypt', 'EG', '+20'),
  CountryCode('Estonia', 'EE', '+372'),
  CountryCode('Ethiopia', 'ET', '+251'),
  CountryCode('Fiji', 'FJ', '+679'),
  CountryCode('Finland', 'FI', '+358'),
  CountryCode('France', 'FR', '+33'),
  CountryCode('Georgia', 'GE', '+995'),
  CountryCode('Germany', 'DE', '+49'),
  CountryCode('Ghana', 'GH', '+233'),
  CountryCode('Greece', 'GR', '+30'),
  CountryCode('Hungary', 'HU', '+36'),
  CountryCode('Iceland', 'IS', '+354'),
  CountryCode('Iran', 'IR', '+98'),
  CountryCode('Iraq', 'IQ', '+964'),
  CountryCode('Ireland', 'IE', '+353'),
  CountryCode('Israel', 'IL', '+972'),
  CountryCode('Italy', 'IT', '+39'),
  CountryCode('Jamaica', 'JM', '+1876'),
  CountryCode('Jordan', 'JO', '+962'),
  CountryCode('Kazakhstan', 'KZ', '+7'),
  CountryCode('Kenya', 'KE', '+254'),
  CountryCode('Kyrgyzstan', 'KG', '+996'),
  CountryCode('Laos', 'LA', '+856'),
  CountryCode('Latvia', 'LV', '+371'),
  CountryCode('Lebanon', 'LB', '+961'),
  CountryCode('Libya', 'LY', '+218'),
  CountryCode('Lithuania', 'LT', '+370'),
  CountryCode('Luxembourg', 'LU', '+352'),
  CountryCode('Madagascar', 'MG', '+261'),
  CountryCode('Maldives', 'MV', '+960'),
  CountryCode('Malta', 'MT', '+356'),
  CountryCode('Mauritius', 'MU', '+230'),
  CountryCode('Mexico', 'MX', '+52'),
  CountryCode('Moldova', 'MD', '+373'),
  CountryCode('Mongolia', 'MN', '+976'),
  CountryCode('Montenegro', 'ME', '+382'),
  CountryCode('Morocco', 'MA', '+212'),
  CountryCode('Myanmar', 'MM', '+95'),
  CountryCode('Netherlands', 'NL', '+31'),
  CountryCode('New Zealand', 'NZ', '+64'),
  CountryCode('Nigeria', 'NG', '+234'),
  CountryCode('North Macedonia', 'MK', '+389'),
  CountryCode('Norway', 'NO', '+47'),
  CountryCode('Panama', 'PA', '+507'),
  CountryCode('Papua New Guinea', 'PG', '+675'),
  CountryCode('Peru', 'PE', '+51'),
  CountryCode('Poland', 'PL', '+48'),
  CountryCode('Portugal', 'PT', '+351'),
  CountryCode('Romania', 'RO', '+40'),
  CountryCode('Russia', 'RU', '+7'),
  CountryCode('Rwanda', 'RW', '+250'),
  CountryCode('Serbia', 'RS', '+381'),
  CountryCode('Seychelles', 'SC', '+248'),
  CountryCode('Slovakia', 'SK', '+421'),
  CountryCode('Slovenia', 'SI', '+386'),
  CountryCode('South Africa', 'ZA', '+27'),
  CountryCode('Spain', 'ES', '+34'),
  CountryCode('Sudan', 'SD', '+249'),
  CountryCode('Sweden', 'SE', '+46'),
  CountryCode('Switzerland', 'CH', '+41'),
  CountryCode('Syria', 'SY', '+963'),
  CountryCode('Taiwan', 'TW', '+886'),
  CountryCode('Tajikistan', 'TJ', '+992'),
  CountryCode('Tanzania', 'TZ', '+255'),
  CountryCode('Trinidad and Tobago', 'TT', '+1868'),
  CountryCode('Tunisia', 'TN', '+216'),
  CountryCode('Turkey', 'TR', '+90'),
  CountryCode('Turkmenistan', 'TM', '+993'),
  CountryCode('Uganda', 'UG', '+256'),
  CountryCode('Ukraine', 'UA', '+380'),
  CountryCode('Uruguay', 'UY', '+598'),
  CountryCode('Uzbekistan', 'UZ', '+998'),
  CountryCode('Venezuela', 'VE', '+58'),
  CountryCode('Yemen', 'YE', '+967'),
  CountryCode('Zambia', 'ZM', '+260'),
  CountryCode('Zimbabwe', 'ZW', '+263'),
];
